# Generated by Django 4.1.7 on 2023-02-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderCrossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('crossing_date', models.DateTimeField(auto_now_add=True)),
                ('nationality', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HealthDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cough', models.BooleanField()),
                ('sore_throat', models.BooleanField()),
                ('difficulty_breathing', models.BooleanField()),
                ('exposure_to_covid', models.BooleanField()),
                ('other_symptoms', models.TextField(blank=True)),
                ('border_crossing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='border.bordercrossing')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
