# Generated by Django 4.1.7 on 2023-02-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_bordercrossing_healthdeclaration_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_administered', models.DateField()),
                ('border_crossing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='border.bordercrossing')),
            ],
        ),
    ]
