# Generated by Django 4.1.7 on 2023-02-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0003_vaccine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthDeclaration',
        ),
    ]
