# Generated by Django 4.1.7 on 2023-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0004_delete_healthdeclaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordercrossing',
            name='passport_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='bordercrossing',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
