# Generated by Django 4.1.7 on 2023-03-23 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0005_alter_bordercrossing_passport_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('dose_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='border.bordercrossing')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='border.vaccine')),
            ],
        ),
    ]
